# one self-contained html page with the headline numbers per segment.

from __future__ import annotations

import json

from src.config import DOCS_DIR, MODELS_DIR

SEGMENTS = {
    "india": "India MSME (synthetic)",
    "sba": "MSME — SBA 7(a)",
    "homecredit": "Retail — Home Credit",
    "gmsc": "Retail — GMSC",
}
BEST_ROW = {
    "india": "lightgbm_raw",
    "sba": "blend_raw",
    "homecredit": "blend_raw",
    "gmsc": "blend_raw",
}


def _load_metrics(key: str) -> dict | None:
    p = MODELS_DIR / key / "metrics.json"
    return json.loads(p.read_text()) if p.exists() else None


def _row_html(key: str, title: str) -> str:
    payload = _load_metrics(key)
    if not payload:
        return ""
    overall = payload["overall"]
    best_key = BEST_ROW.get(key, next(iter(overall)))
    m = overall.get(best_key) or next(iter(overall.values()))
    cal_key = best_key.replace("_raw", "_calibrated")
    cal = overall.get(cal_key, m)
    return (
        f"<tr><td>{title}</td>"
        f"<td>{m['roc_auc']:.3f}</td>"
        f"<td><strong>{m['capture_top_decile']:.0%}</strong></td>"
        f"<td>{m.get('lift_top_decile', 0):.1f}x</td>"
        f"<td>{cal['brier']:.3f}</td>"
        f"<td>{int(m['n']):,}</td></tr>"
    )


def main() -> None:
    rows = "".join(_row_html(k, t) for k, t in SEGMENTS.items())
    ablation_note = ""
    if (MODELS_DIR / "india" / "ablation.png").exists():
        ablation_note = (
            "<p><strong>India ablation staircase</strong> — structured-only → "
            "+GST/AA → +officer notes → +graph (see models_store/india/ablation.png).</p>"
        )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>DRISHTI — Bench card</title>
<style>
body {{ font-family: system-ui, sans-serif; background: #0f1419; color: #e8eaed; margin: 2rem; }}
h1 {{ color: #7dd3c0; }}
table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
th, td {{ border: 1px solid #333; padding: 0.5rem 0.75rem; text-align: left; }}
th {{ background: #1a2332; }}
.callout {{ background: #1a2332; border-left: 4px solid #e8732c; padding: 1rem; margin: 1rem 0; }}
.muted {{ color: #9aa0a6; font-size: 0.9rem; }}
</style>
</head>
<body>
<h1>DRISHTI — Bench card</h1>
<p class="muted">IDBI Innovate 26 · PS4 · Auto-generated from models_store metrics</p>

<div class="callout">
<strong>Why not raw accuracy?</strong> At low default rates, class accuracy is dominated by
the non-default majority. DRISHTI reports <em>capture@top-10%</em> and lift — the share of
eventual defaulters caught when reviewing the riskiest decile — alongside calibrated Brier scores.
</div>

<table>
<thead><tr>
<th>Segment</th><th>AUC</th><th>Capture@10%</th><th>Lift</th><th>Brier (cal)</th><th>n</th>
</tr></thead>
<tbody>
{rows or '<tr><td colspan="6">No metrics — run training pipelines first.</td></tr>'}
</tbody>
</table>

{ablation_note}

<p class="muted">Generated by src.pipelines.make_bench_card</p>
</body>
</html>
"""
    out = DOCS_DIR / "bench_card.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
