/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as ContagionRouteImport } from './routes/contagion'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as UnderwriteRouteImport } from './routes/underwrite'
import { Route as BorrowersIdRouteImport } from './routes/borrowers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContagionRoute = ContagionRouteImport.update({
  id: '/contagion',
  path: '/contagion',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderwriteRoute = UnderwriteRouteImport.update({
  id: '/underwrite',
  path: '/underwrite',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowersIdRoute = BorrowersIdRouteImport.update({
  id: '/borrowers/$id',
  path: '/borrowers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/batch': typeof BatchRoute
  '/branches': typeof BranchesRoute
  '/contagion': typeof ContagionRoute
  '/governance': typeof GovernanceRoute
  '/guide': typeof GuideRoute
  '/scenario': typeof ScenarioRoute
  '/underwrite': typeof UnderwriteRoute
  '/borrowers/$id': typeof BorrowersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/batch': typeof BatchRoute
  '/branches': typeof BranchesRoute
  '/contagion': typeof ContagionRoute
  '/governance': typeof GovernanceRoute
  '/guide': typeof GuideRoute
  '/scenario': typeof ScenarioRoute
  '/underwrite': typeof UnderwriteRoute
  '/borrowers/$id': typeof BorrowersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/batch': typeof BatchRoute
  '/branches': typeof BranchesRoute
  '/contagion': typeof ContagionRoute
  '/governance': typeof GovernanceRoute
  '/guide': typeof GuideRoute
  '/scenario': typeof ScenarioRoute
  '/underwrite': typeof UnderwriteRoute
  '/borrowers/$id': typeof BorrowersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/batch'
    | '/branches'
    | '/contagion'
    | '/governance'
    | '/guide'
    | '/scenario'
    | '/underwrite'
    | '/borrowers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/batch'
    | '/branches'
    | '/contagion'
    | '/governance'
    | '/guide'
    | '/scenario'
    | '/underwrite'
    | '/borrowers/$id'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/batch'
    | '/branches'
    | '/contagion'
    | '/governance'
    | '/guide'
    | '/scenario'
    | '/underwrite'
    | '/borrowers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BatchRoute: typeof BatchRoute
  BranchesRoute: typeof BranchesRoute
  ContagionRoute: typeof ContagionRoute
  GovernanceRoute: typeof GovernanceRoute
  GuideRoute: typeof GuideRoute
  ScenarioRoute: typeof ScenarioRoute
  UnderwriteRoute: typeof UnderwriteRoute
  BorrowersIdRoute: typeof BorrowersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contagion': {
      id: '/contagion'
      path: '/contagion'
      fullPath: '/contagion'
      preLoaderRoute: typeof ContagionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/underwrite': {
      id: '/underwrite'
      path: '/underwrite'
      fullPath: '/underwrite'
      preLoaderRoute: typeof UnderwriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrowers/$id': {
      id: '/borrowers/$id'
      path: '/borrowers/$id'
      fullPath: '/borrowers/$id'
      preLoaderRoute: typeof BorrowersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  BatchRoute: BatchRoute,
  BranchesRoute: BranchesRoute,
  ContagionRoute: ContagionRoute,
  GovernanceRoute: GovernanceRoute,
  GuideRoute: GuideRoute,
  ScenarioRoute: ScenarioRoute,
  UnderwriteRoute: UnderwriteRoute,
  BorrowersIdRoute: BorrowersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
